src/main/java/com/ssj/model/base/CommentReply.java
package com.ssj.model.base;

import com.ssj.model.user.User;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import java.util.Date;

/**
 * Class javadoc comment here...
 *
 * @author sam
 * @version $Id$
 */
@MappedSuperclass
public abstract class CommentReply<CommentType extends Comment<?>> {

//  public static final int COMMENT_TOTAL_MAX_LENGTH = 4000;
  private static final int COMMENT_TEXT_MAX_LENGTH = 1600;

  private int id;

  private User user;

  private String commentText;
  private String moreCommentText;

  private Date createDate = new Date();
  private Date changeDate = createDate;

  public CommentReply() {
  }

  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  public int getId() {
    return id;
  }

  public void setId(int id) {
    this.id = id;
  }

  @Transient
  public abstract CommentType getOriginalComment();

  public abstract void setOriginalComment(CommentType originalComment);

  //  @NotEmpty(message = "Body content is required")
  @Length(min = 4, max = 4000, message = "Body content must be 4 to 4000 characters")
  @Column(nullable = false)
  @Lob
  public String getCommentText() {
    return commentText;
  }

  public void setCommentText(String commentText) {
    this.commentText = commentText;
  }

  @Lob
  public String getMoreCommentText() {
    return moreCommentText;
  }

  public void setMoreCommentText(String moreCommentText) {
    this.moreCommentText = moreCommentText;
  }

  @Column(updatable = false)
  @Temporal(TemporalType.TIMESTAMP)
  public Date getCreateDate() {
    return createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }

  @Temporal(TemporalType.TIMESTAMP)
  public Date getChangeDate() {
    return changeDate;
  }

  public void setChangeDate(Date changeDate) {
    this.changeDate = changeDate;
  }

  @ManyToOne
  @JoinColumn(name = "userId", nullable = false)
  public User getUser() {
    return user;
  }

  public void setUser(User user) {
    this.user = user;
  }

  public void mergeContent() {
    if (commentText != null) {
      if (moreCommentText != null) {
        commentText += moreCommentText;
        moreCommentText = null;
      }
    } else if (moreCommentText != null) {
      commentText = moreCommentText;
      moreCommentText = null;
    }
  }

  public void splitContent() {
    if (commentText == null || commentText.length() <= COMMENT_TEXT_MAX_LENGTH) {
      moreCommentText = null;
    } else {
      moreCommentText = commentText.substring(COMMENT_TEXT_MAX_LENGTH);
      commentText = commentText.substring(0, COMMENT_TEXT_MAX_LENGTH);
    }
  }

}

src/main/java/com/ssj/model/base/Rateable.java
package com.ssj.model.base;

import javax.persistence.Column;
import javax.persistence.MappedSuperclass;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import java.text.DecimalFormat;
import java.util.Date;

/**
 * Class javadoc comment here...
 *
 * @author sam
 * @version $Id$
 */
@MappedSuperclass
public abstract class Rateable {

  public static final DecimalFormat RATING_FORMAT = new DecimalFormat("#0.00");

  public static final int MIN_RATINGS = 5; //number of ratings required before average rating is public

  @Column(nullable = false)
  private int numRatings;
  private Float rating;

  @Temporal(TemporalType.TIMESTAMP)
  private Date lastRated;

  public int getNumRatings() {
//    return (ratings.size());
    return numRatings;
  }

  public void setNumRatings(int numRatings) {
    this.numRatings = numRatings;
  }

  public boolean showRating() {
    return getNumRatings() >= MIN_RATINGS;
  }

  public boolean isShowRating() {
    return showRating();
  }

  public int getNumRatingsNeeded() {
    return Math.max(MIN_RATINGS - getNumRatings(), 0);
  }

  public Float getRating() {
    return (rating == null ? 0f : rating);
  }

  public void setRating(Float rating) {
    this.rating = rating;
  }

  public String getRatingString() {
    return RATING_FORMAT.format(getRating());
  }

  public Date getLastRated() {
    return lastRated;
  }

  public void setLastRated(Date lastRated) {
    this.lastRated = lastRated;
  }
}

src/main/java/com/ssj/model/playlist/Playlist.java
package com.ssj.model.playlist;

import com.ssj.model.user.User;
import com.ssj.model.user.FavoritePlaylist;
import com.ssj.model.base.Rateable;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;
import java.util.Date;
import java.util.LinkedHashSet;

/**
 * Class javadoc comment here...
 *
 * @author sam
 * @version $Id$
 */
@Entity
public class Playlist extends Rateable {

  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "playlistId")
  private int id;

  @ManyToOne
  @JoinColumn(name = "userId", nullable = false)
  private User user;

//  @NotEmpty(message = "Please enter a title")
  @Length(min = 2, max = 256, message = "Title must be 2 to 256 characters long")
  @Column(nullable = false)
  private String title;

  @Length(max = 2000, message = "Description can not contain more than 2000 characters")
  @Lob
  private String description;

  @Column(nullable = false, columnDefinition = "BOOLEAN")
  private boolean publiclyAvailable = true;

  @Column(nullable = false)
  private int numItems; // updated by a trigger

  @OneToMany(mappedBy = "playlist", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
  @OrderBy("ordinal asc")
  @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
  private Set<PlaylistItem> items = new HashSet<PlaylistItem>();

  @OneToMany(mappedBy = "playlist", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
  @OrderBy("createDate desc")
  @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
  private Set<PlaylistComment> comments = new LinkedHashSet<PlaylistComment>();

  @OneToMany(mappedBy = "playlist", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
  @OrderBy("createDate desc")
  @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
  private Set<PlaylistRating> ratings = new LinkedHashSet<PlaylistRating>();

  // this is really just here for now to handle deleting these when deleting a playlist
  @OneToMany(mappedBy = "playlist", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
  @OrderBy("createDate desc")
  @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
  private Set<FavoritePlaylist> favorites = new LinkedHashSet<FavoritePlaylist>();

  @Column(updatable = false)
  @Temporal(TemporalType.TIMESTAMP)
  private Date createDate = new Date();

  @Temporal(TemporalType.TIMESTAMP)
  private Date changeDate = createDate;

  public Playlist() {
  }

  public int getId() {
    return id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public User getUser() {
    return user;
  }

  public void setUser(User user) {
    this.user = user;
  }

  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public boolean isPubliclyAvailable() {
    return publiclyAvailable;
  }

  public void setPubliclyAvailable(boolean publiclyAvailable) {
    this.publiclyAvailable = publiclyAvailable;
  }

  public Set<PlaylistItem> getItems() {
    return items;
  }

  public void setItems(Set<PlaylistItem> items) {
    this.items = items;
  }

  public Date getChangeDate() {
    return changeDate;
  }

  public void setChangeDate(Date changeDate) {
    this.changeDate = changeDate;
  }

  public Date getCreateDate() {
    return createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;

    Playlist playlist = (Playlist) o;

    return id == playlist.id;

  }

  public int hashCode() {
    int result;
    result = id;
    result = 31 * result + (user != null ? user.hashCode() : 0);
    result = 31 * result + (title != null ? title.hashCode() : 0);
    result = 31 * result + (description != null ? description.hashCode() : 0);
    result = 31 * result + (publiclyAvailable ? 1 : 0);
//    result = 31 * result + (items != null ? items.hashCode() : 0);
    return result;
  }

  public Set<PlaylistRating> getRatings() {
    return ratings;
  }

  public void setRatings(Set<PlaylistRating> ratings) {
    this.ratings = ratings;
  }

  public int getNumItems() {
    return numItems;
  }

  public void setNumItems(int numItems) {
    this.numItems = numItems;
  }

  public Set<PlaylistComment> getComments() {
    return comments;
  }

  public void setComments(Set<PlaylistComment> comments) {
    this.comments = comments;
  }

  public Set<FavoritePlaylist> getFavorites() {
    return favorites;
  }

  public void setFavorites(Set<FavoritePlaylist> favorites) {
    this.favorites = favorites;
  }
}

src/main/java/com/ssj/model/playlist/PlaylistComment.java
package com.ssj.model.playlist;

import com.ssj.model.base.Comment;

import javax.persistence.*;
import java.util.Set;

/**
 * Class javadoc comment here...
 *
 * @author sam
 * @version $Id$
 */
@Entity
@AttributeOverride(name = "id", column = @Column(name = "playlistCommentId"))
public class PlaylistComment extends Comment<Playlist> {

  @ManyToOne
  @JoinColumn(name = "playlistId", nullable = false)
  private Playlist playlist;

  @OneToMany(mappedBy = "originalComment", cascade = CascadeType.ALL, orphanRemoval = true)
  @OrderBy("createDate desc")
  private Set<PlaylistCommentReply> replies;

  public Playlist getPlaylist() {
    return playlist;
  }

  public void setPlaylist(Playlist playlist) {
    this.playlist = playlist;
  }

  @Override
  public Playlist getItem() {
    return getPlaylist();
  }

  @Override
  public void setItem(Playlist item) {
    setPlaylist(item);
  }

  public Set<PlaylistCommentReply> getReplies() {
    return replies;
  }

  public void setReplies(Set<PlaylistCommentReply> replies) {
    this.replies = replies;
  }
}

src/main/java/com/ssj/model/playlist/PlaylistCommentReply.java
package com.ssj.model.playlist;

import com.ssj.model.base.CommentReply;

import javax.persistence.*;

/**
 * Class javadoc comment here...
 *
 * @author sam
 * @version $Id$
 */
@Entity
//@Access(AccessType.PROPERTY)
@AttributeOverride(name = "id", column = @Column(name = "playlistCommentReplyId"))
public class PlaylistCommentReply extends CommentReply<PlaylistComment> {

  private PlaylistComment playlistComment;

/*
  public PlaylistComment getPlaylistComment() {
    return playlistComment;
  }

  public void setPlaylistComment(PlaylistComment playlistComment) {
    this.playlistComment = playlistComment;
  }
*/

  @ManyToOne(targetEntity = PlaylistComment.class)
  @JoinColumn(name = "playlistCommentId", nullable = false)
  @Override
  public PlaylistComment getOriginalComment() {
    return playlistComment;
  }

  @Override
  public void setOriginalComment(PlaylistComment originalComment) {
    playlistComment = originalComment;
  }
}

src/main/java/com/ssj/model/playlist/PlaylistItem.java
package com.ssj.model.playlist;

import com.ssj.model.song.Song;
import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import java.util.Date;

/**
 * Class javadoc comment here...
 *
 * @author sam
 * @version $Id$
 */
@SuppressWarnings({"RedundantIfStatement"})
@Entity
public class PlaylistItem {

  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(name = "playlistItemId")
  private int id;
  @ManyToOne
  @JoinColumn(name = "playlistId", nullable = false)
  private Playlist playlist;
  @ManyToOne
  @JoinColumn(name = "songId", nullable = false)
  private Song song;

  @Length(max = 1000, message = "Note can not contain more than 1000 characters")
  @Lob
  private String note;
  private int ordinal;

  @Column(updatable = false)
  @Temporal(TemporalType.TIMESTAMP)
  private Date createDate = new Date();
  @Temporal(TemporalType.TIMESTAMP)
  private Date changeDate = createDate;

  public PlaylistItem() {
  }

  public int getId() {
    return id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public Playlist getPlaylist() {
    return playlist;
  }

  public void setPlaylist(Playlist playlist) {
    this.playlist = playlist;
  }

  public Song getSong() {
    return song;
  }

  public void setSong(Song song) {
    this.song = song;
  }

  public int getOrdinal() {
    return ordinal;
  }

  public void setOrdinal(int ordinal) {
    this.ordinal = ordinal;
  }

  public String getNote() {
    return note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  public Date getChangeDate() {
    return changeDate;
  }

  public void setChangeDate(Date changeDate) {
    this.changeDate = changeDate;
  }

  public Date getCreateDate() {
    return createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;

    PlaylistItem that = (PlaylistItem) o;

    if (ordinal != that.ordinal) return false;
    if (playlist != null ? !playlist.equals(that.playlist) : that.playlist != null) return false;
    if (song != null ? !song.equals(that.song) : that.song != null) return false;

    return true;
  }

  public int hashCode() {
    int result;
    result = id;
    result = 31 * result + (playlist != null ? playlist.hashCode() : 0);
    result = 31 * result + (song != null ? song.hashCode() : 0);
    result = 31 * result + ordinal;
    result = 31 * result + (note != null ? note.hashCode() : 0);
    return result;
  }
}

src/main/java/com/ssj/model/playlist/PlaylistRating.java
package com.ssj.model.playlist;

import com.ssj.model.base.Rating;

import javax.persistence.*;

/**
 * Class javadoc comment here...
 *
 * @author sam
 * @version $Id$
 */
@Entity
@AttributeOverride(name = "id", column = @Column(name = "playlistRatingId"))
public class PlaylistRating extends Rating<Playlist> {

  @ManyToOne
  @JoinColumn(name = "playlistId", nullable = false)
  private Playlist playlist;

  public Playlist getPlaylist() {
    return playlist;
  }

  public void setPlaylist(Playlist playlist) {
    this.playlist = playlist;
  }

  @Override
  public Playlist getItem() {
    return getPlaylist();
  }

  @Override
  public void setItem(Playlist item) {
    setPlaylist(item);
  }
}

src/main/java/com/ssj/model/playlist/search/PlaylistCommentReplySearch.java
package com.ssj.model.playlist.search;

import com.ssj.search.SearchBase;
import com.ssj.model.playlist.PlaylistComment;

/**
 * Class javadoc comment here...
 *
 * @author sam
 * @version $Id$
 */
public class PlaylistCommentReplySearch extends SearchBase {

  public static final int ORDER_BY_CREATE_DATE = 0;

  private static final String DEFAULT_NAME = "Reply Search";

  private static final int DEFAULT_RESULTS_PER_PAGE = 10;

  private int id;

  private String name = DEFAULT_NAME;

  private PlaylistComment originalComment;

  private String commentText;

  private String userDisplayName;

  private Integer notByIgnoredUsers;

  public PlaylistCommentReplySearch() {
    super();
    setResultsPerPage(DEFAULT_RESULTS_PER_PAGE);
  }

  public int getId() {
    return id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PlaylistComment getOriginalComment() {
    return originalComment;
  }

  public void setOriginalComment(PlaylistComment originalComment) {
    this.originalComment = originalComment;
  }

  public String getCommentText() {
    return commentText;
  }

  public void setCommentText(String commentText) {
    this.commentText = commentText;
  }

  public String getUserDisplayName() {
    return userDisplayName;
  }

  public void setUserDisplayName(String userDisplayName) {
    this.userDisplayName = userDisplayName;
  }

  public Integer getNotByIgnoredUsers() {
    return notByIgnoredUsers;
  }

  public void setNotByIgnoredUsers(Integer notByIgnoredUsers) {
    this.notByIgnoredUsers = notByIgnoredUsers;
  }
}

src/main/java/com/ssj/model/playlist/search/PlaylistCommentReplySearchFactory.java
package com.ssj.model.playlist.search;

/**
 * Class javadoc comment here...
 *
 * @author sam
 * @version $Id$
 */
public class PlaylistCommentReplySearchFactory {

  public static final int SEARCH_ID_RECENT = -1;

  public static PlaylistCommentReplySearch getSearch(int searchId) {
    PlaylistCommentReplySearch search;
    switch(searchId) {
      case SEARCH_ID_RECENT:
      default:
        search = getRecentRepliesSearch();
        break;
    }
    return search;
  }

  public static final String NAME_RECENT_REPLIES = "Recent Replies to Comments";

  private static PlaylistCommentReplySearch getRecentRepliesSearch() {
    PlaylistCommentReplySearch search = new PlaylistCommentReplySearch();

    search.setName(NAME_RECENT_REPLIES);
    search.setResultsPerPage(10);
    search.setResultsPerNextPage(25);
    search.setOrderBy(PlaylistCommentSearch.ORDER_BY_CREATE_DATE);
    search.setId(SEARCH_ID_RECENT);

    return search;
  }
}

src/main/webapp/WEB-INF/jsp/user/add_artist.jsp
<%@ include file="/WEB-INF/jsp/include/taglibs.jsp" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<div id="artistFormDiv">
<form:form id="addArtistForm" commandName="artist" onsubmit="saveArtist(); return false;">
<div id="errorsDiv">
  <form:errors path="*" cssClass="errors" element="div"/>
</div>
<table id="artistTable" width="100%" cellspacing="4">
  <tr>
    <td><b>Add Artist</b></td>
    <%-- IE doesn't like colspan plus specified column width :( --%>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Name:</td>
    <td><form:input path="name" id="name" cssStyle="width:100%"/></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td align="right">
      <br>
      <input type="button" name="cancelBtn" class="commentButton" value="Cancel" onclick="cancelArtist()"/>
      <input type="submit" name="submitBtn" class="commentButton" value="Save"/>
    </td>
  </tr>
</table>
</form:form>
</div>
<%-- causes an error in IE :(
<script type="text/javascript" language="JavaScript"><!--
//alert('test');
setTimeout('document.forms.addArtistForm.name.focus()', 500);
//--></script>
--%>

src/main/webapp/WEB-INF/jsp/user/add_playlist.jsp
<%@ include file="/WEB-INF/jsp/include/taglibs.jsp" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<div id="playlistFormDiv">
<form:form id="addPlaylistForm" commandName="playlist" onsubmit="savePlaylist(); return false;">

<input type="hidden" name="songId" value="<c:out value="param.songId"/>">

<div id="errorsDiv">
  <form:errors path="*" cssClass="errors" element="div"/>
</div>

<%-- TODO figure out if I can use valang here or not --%>
<!--<valang:validate commandName="playlist"/>-->

<table id="playlistTable" width="100%" cellspacing="4">
  <tr>
    <td><b>Add Playlist</b></td>
  </tr>
  <tr>
    <td><form:input path="title" id="title" cssStyle="float:right;width:80%"/>Title:</td>
  </tr>
  <tr>
    <td>
      Description (optional):<br>
      <form:textarea path="description" id="description" cssStyle="width:100%;height:100px;"/>
      <div class="allowedTags">Allowed HTML: &lt;i&gt; &lt;font&gt; &lt;b&gt; &lt;u&gt; &lt;a&gt; &lt;br&gt; &lt;blockquote&gt; &lt;ul&gt; &lt;ol&gt; &lt;li&gt; &lt;em&gt; &lt;strong&gt; &lt;sup&gt; &lt;sub&gt; &lt;credit&gt;</div>
    </td>
  </tr>
  <tr>
    <td>
      <br>
      <span style="float:right">
        <input type="button" name="cancelBtn" class="commentButton" value="Cancel" onclick="cancelPlaylist()"/>
        <input type="submit" name="submitBtn" class="commentButton" value="Save"/>
      </span>
    </td>
  </tr>
</table>
</form:form>
</div>
<script>setTimeout('document.forms.addPlaylistForm.title.focus()', 500);</script>
<script>TextareaLimiter.addLimiter("description", 2000);</script>

src/main/webapp/WEB-INF/jsp/user/edit_song.jsp
<%@ include file="/WEB-INF/jsp/include/taglibs.jsp" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<form:form name="editSongForm" id="editSongForm" cssClass="cmxform" commandName="song" onsubmit="saveSong(); return false;">
  <form:hidden path="id"/>
  <form:hidden path="duration" id="duration"/>
  <form:hidden path="bandcampTrackId" id="bandcampTrackId"/>
<div id="errorsDiv">
  <form:errors path="*" cssClass="errors" element="div"/>
</div>
<table class="songInfoTable">
  <tr class="grayBottom">
    <td class="nowrap" align="right" valign="top"><b>Song Info:</b>&nbsp;</td>
    <td>
      <c:url var="sArtistLink" value="/artists/${song.artist.nameForUrl}-${song.artist.id}"/>
      <span>'<c:out value="${song.title}"/>' by <a href="<c:out value="${sArtistLink}"/>"><c:out value="${song.artist.name}"/></a></span>
    </td>
  </tr>
  <tr class="oddRow">
    <td class="nowrap" align="right">Avg. Rating:&nbsp;</td>
    <td><span id="rating"<c:if test="${song.showRating ne true}">
      style="display:none"</c:if>><c:out value="${song.ratingString}"/></span><span
      id="needsRatings" class="needsRatings"<c:if test="${song.showRating}">
      style="display:none"</c:if>>This song needs [ <b id="numRatingsNeeded"><c:out value="${song.numRatingsNeeded}"/></b> ] more ratings.</span></td>
  </tr>
  <tr class="evenRow">
    <td class="nowrap" align="right"># of Ratings:&nbsp;</td>
    <td id="numRatings"><c:out value="${song.numRatings}"/></td>
  </tr>
  <tr class="oddRow">
    <td align="right">Posted:&nbsp;</td>
    <td><fmt:formatDate value="${song.createDate}" pattern="yyyy-MM-dd HH:mm:ss"/></td>
  </tr>
  <tr class="evenRow">
    <td align="right">Title:&nbsp;</td>
    <td><form:input path="title" id="title" cssClass="wideInput"/></td>
  </tr>
  <tr class="oddRow">
    <td align="right">MP3 URL:&nbsp;</td>
    <td><form:input path="url" id="url" cssClass="wideInput"/></td>
  </tr>
  <tr class="evenRow">
    <td align="right">Album:&nbsp;</td>
    <td><form:input path="album" id="album" cssClass="wideInput"/></td>
  </tr>
  <tr class="oddRow">
    <td align="right">Track #:&nbsp;</td>
    <td><form:input path="albumTrackNumber" id="albumTrackNumber" cssClass="wideInput"/></td>
  </tr>
  <tr class="evenRow">
    <td align="right">Bandcamp URL:&nbsp;</td>
    <td><form:input path="bandcampUrl" id="bandcampUrl" cssClass="wideInput"/></td>
  </tr>
<%--
  <tr class="oddRow">
    <td>&nbsp;</td>
    <td>
      <input type="button" class="subtmiBtn" style="width:auto" onclick="return loadFromBandcamp(this.form.bandcampUrl.value)" name="loadFromBandcampBtn" value="Copy Song Info From Bandcamp">
      <span id="copyFromBandcampSpinner" style="display:none"><img src="<c:url value="/img/ajax-loader.gif"/>" width="16" height="16" alt="..." title="Working..."></span>
    </td>
  </tr>
--%>
  <tr class="oddRow">
    <td align="right">SoundCloud URL:&nbsp;</td>
    <td><form:input path="soundCloudUrl" id="soundCloudUrl" cssClass="wideInput"/></td>
  </tr>
<%--
  <tr class="oddRow">
    <td>&nbsp;</td>
    <td>
      <input type="button" class="subtmiBtn" style="width:auto" onclick="return loadFromBandcamp(this.form.bandcampUrl.value)" name="loadFromBandcampBtn" value="Copy Song Info From Bandcamp">
      <span id="copyFromBandcampSpinner" style="display:none"><img src="<c:url value="/img/ajax-loader.gif"/>" width="16" height="16" alt="..." title="Working..."></span>
    </td>
  </tr>
--%>
  <tr class="evenRow">
    <td align="right" valign="top">Info:&nbsp;</td>
    <td valign="top"><form:textarea path="info" id="info" cssClass="wideInput"/></td>
  </tr>
  <tr class="evenRow">
    <td>&nbsp;</td>
    <td>
      <div class="allowedTags">&lt;i&gt; &lt;font&gt; &lt;b&gt; &lt;u&gt; &lt;a&gt; &lt;br&gt; &lt;em&gt; &lt;strong&gt; &lt;sup&gt; &lt;sub&gt; &lt;credit&gt;</div>
    </td>
  </tr>
  <tr class="evenRow">
    <td align="right" valign="top">More Info:&nbsp;</td>
    <td valign="top"><form:textarea path="moreInfo" id="moreInfo" cssClass="wideInput"/></td>
  </tr>
  <tr class="evenRow">
    <td>&nbsp;</td>
    <td>
      <div class="allowedTags">&lt;i&gt; &lt;font&gt; &lt;b&gt; &lt;u&gt; &lt;a&gt; &lt;br&gt; &lt;blockquote&gt; &lt;ul&gt; &lt;ol&gt;<br>
        &lt;li&gt; &lt;em&gt; &lt;strong&gt; &lt;sup&gt; &lt;sub&gt; &lt;credit&gt;</div>
    </td>
  </tr>
  <tr class="evenRow">
    <td class="nowrap" align="right">Show Song:&nbsp;</td>
    <td><form:checkbox path="showSong" id="showSong"/></td>
  </tr>
  <tr class="evenRow">
    <td colspan="2">
      <span style="float:right">
        <input type="button" name="cancelBtn" value="Cancel" onclick="cancelEdit()"/>
        <input type="submit" name="submitBtn" value="Save"/>
      </span>
      <input type="button" name="deleteBtn" value="Delete" onclick="deleteSong()"/>
    </td>
  </tr>
  <tr class="evenRow">
    <td colspan="2"><a class="songLink" href="<c:out value="${song.url}"/>" title="Hear/Download '<c:out value="${song.title}"/>'">MP3</a></td>
  </tr>
</table>
</form:form>
<script>TextareaLimiter.addLimiter('info', 1000)</script>
<script>TextareaLimiter.addLimiter('moreInfo', 3000)</script>